# Generated by Django 5.1.3 on 2024-11-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
