# Generated by Django 5.1.3 on 2024-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_user_fname_user_lname_user_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='Unknown'),
            preserve_default=False,
        ),
    ]
