# Generated by Django 5.1.3 on 2024-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
