# Generated by Django 5.1.3 on 2024-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_checkinmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmodel',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='bookId',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='fine',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='rent',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='userId',
            field=models.IntegerField(max_length=255),
        ),
    ]
