# Generated by Django 5.1.3 on 2024-12-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_checkinmodel_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmodel',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='depositedIn',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='checkinmodel',
            name='shelve',
        ),
    ]
